# name: Generate Sales Data

# on:
#   schedule:
#     - cron: '0 0 * * *'  # Runs daily at midnight
#   workflow_dispatch:      # Allows manual trigger

# jobs:
#   generate-data:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3
#       with:
#         fetch-depth: 0

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.x'

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pandas

#     - name: Run script
#       run: python generate_sales.py

#     - name: Commit and push new data file
#       run: |
#         git config --global user.name 'github-actions[bot]'
#         git config --global user.email 'github-actions[bot]@users.noreply.github.com'
#         git add *.csv
#         timestamp=$(date '+%Y-%m-%d %H:%M:%S')
#         git commit -m "Sales data update: ${timestamp}" || echo "No changes to commit"
#         git push origin main

#     - name: Upload CSV as artifact
#       uses: actions/upload-artifact@v3
#       with:
#         name: sales-data-${{ github.run_number }}
#         path: '*.csv'
#         retention-days: 30


name: Generate Sales Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:      # Allows manual trigger
  push:
    branches:
      - 'master'          # Trigger the workflow on push to the master branch

permissions:
  contents: write  # Allow the workflow to push to the repository

jobs:
  generate-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: List files in the repository
      run: |
        echo "Listing files in the current directory:"
        ls -al

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check if requirements.txt exists
      run: |
        if [ ! -f "requirements.txt" ]; then
          echo "Error: requirements.txt not found!"
          exit 1
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure it is in the root directory

    - name: Run script
      run: |
        python generate_sales.py  # Make sure the path is correct

    - name: Commit and push new data file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add *.csv
        timestamp=$(date '+%Y-%m-%d %H:%M:%S')
        git commit -m "Sales data update: ${timestamp}" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/OkiriGabriel/Python-script-that-generates-a-CSV-file-with-random-data-workflow.git HEAD:master

    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sales-data-${{ github.run_number }}
        path: '*.csv'
        retention-days: 30
